Enable Cruise Control to collect metrics from low traffic clusters by default
linkedin/cruise-control pull request #1369
Opened 2020-11-02 18:47 UTC by efeg

Cruise Control (CC) can fail to collect sufficient metrics from low traffic Kafka clusters for an extended period of time, which would make CC unable to handle model-based (e.g. get cluster `load`) or goal-based (`rebalance` the cluster using the default goals) operations – e.g.
```
Error processing GET request '/partition_load' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1603951915056] for aggregation options (minValidEntityRatio=0.98, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=55498, granularity=ENTITY)'.
```

We have already exposed the relevant config to fix similar observed issues in https://github.com/linkedin/cruise-control/pull/730. However, the default config value has not been updated, which requires users to manually change the config. This patch updates the default value of the relevant config to a value that enable collection of metrics from low traffic clusters by default.

2020-11-02 21:12 UTC, wyuka commented on cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
> +  public static final int DEFAULT_CRUISE_CONTROL_METRICS_REPORTER_LINGER_MS = 5000;
We might want to go with the convention and write it as 5 * 1000.

2020-11-03 20:30 UTC, Lincong requested changes

2020-11-03 20:30 UTC, Lincong commented on cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
> +  public static final int DEFAULT_CRUISE_CONTROL_METRICS_REPORTER_LINGER_MS = 5 * 1000;
I highly recommend using `TimeUnit` to set default values for all time-related parameters. For example `DEFAULT_CRUISE_CONTROL_METRICS_REPORTER_LINGER_MS  = TimeUnit.SECONDS.toMillis(5);`

2020-11-03 20:34 UTC, Lincong commented on cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporterConfig.java
> +  public static final int DEFAULT_CRUISE_CONTROL_METRICS_REPORTER_LINGER_MS = 5 * 1000;
I will close this issue and I will create another PR to fix this issue.

2020-11-03 20:34 UTC, Lincong approved these changes

2020-11-03 22:00 UTC, merged