adding missing EasyMock.verify calls
linkedin/cruise-control pull request #1414
Opened 2020-12-08 23:49 UTC by jakehell

This PR resolves #1408

2021-03-18 18:49 UTC, efeg requested changes
I see missing cases in both the modified and unmodified tests -- i.e. in some cases `verify` does not include all mocks (left an example instance in review), in others `verify` is completely missing (e.g. verify for `HttpServletRequest` mock in `UserTaskManagerTest#prepareRequest(HttpSession, String, String, Map<String, String []>)`).

Can we add the missing EasyMock.verify in relevant unit tests?

2021-03-18 18:49 UTC, efeg commented on cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManagerTest.java
> +    EasyMock.verify(mockHttpServletResponse);
Should this be `EasyMock.verify(mockHttpServletResponse, mockHttpSession, mockUUIDGenerator);`?

2021-08-19 00:40 UTC, efeg commented
Closing this PR due to inactivity.

2021-08-19 00:40 UTC, closed without merging

2024-05-13 22:02 UTC, shreeraam-ramachandran commented
Hi can i work on this issue