feat: Retry metrics reporter producer creation
linkedin/cruise-control pull request #1772
Opened 2022-01-11 19:00 UTC by amberimam

Add the ability for the metrics reporter to retry creating the producer while starting up. The number of retries is a configurable value, called "cruise.control.metrics.reporter.create.retries". The default number of retries is 2.

2022-01-18 13:19 UTC, amberimam commented
Hi @efeg, can you please review this PR when you get a chance? Thanks in advance!

2022-01-28 00:00 UTC, efeg requested changes
@amberimam Thanks for the PR -- left some comments.

2022-02-01 17:20 UTC, amberimam commented on cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
> +
Thanks for your review! Will fix.

2022-02-01 17:22 UTC, amberimam commented on cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java
> +            LOG.warn("Unable to create Cruise Control metrics producer. ", e.getCause());
yes, will change.

2022-02-01 17:24 UTC, amberimam commented
Thank you so much for your comments @efeg, I believe I have addressed them all.

2022-02-01 21:54 UTC, efeg approved these changes
@amberimam Thanks for the PR - LGTM.

2022-02-01 21:56 UTC, merged