Fix: intra.broker.goals cannot be configured as default.goals
linkedin/cruise-control pull request #2221
Opened 2024-11-08 12:16 UTC by k0b3rIT

## Summary
1. Why: KafkaCruiseControlConfig sanity checks prevent to configure inter broker goals as default goals.
2. What: Modify the sanity check to allow adding intra broker goals to the `default.goals`

## Expected Behavior
I can add (enable) goals to the `default.goals` list from both the intra and inter broker goals

## Actual Behavior
Sanity checks ensure the following rules:
- **goals and intra broker goals should be disjoint** (an intra broker goal cant be in the `goals` and the `intra.broker.goals` at the same time)
- **`default.goals` should be a subset of `goals`** (As a result of this, we could not add intra broker goal to the `default.goals`)
- **`intra.broker.goals` cant be empty** (you could not move all the intra broker roles to the goals)

We could not add intra goal to the `default.goals` without a trick (see in the workaround section) 

## Steps to Reproduce
Try to enable an intra broker goal by adding it to the `default. goals`

## Known Workarounds
You can remove 1 intra broker goal from the `intra.broker.goals` config and add that to the `goals` (keep in mind that the other one should be in the `intra.broker.goals` as the list cant be empty) this way you can add that 1 goal to the `default.goals` and enable it

Note that this way we still cant enable both of the currently available intra broker goals as 1 have to be in the intra.broker.goals list to avoid hitting the mentioned sanity check. So only 1 intra goal at a time.

## Categorization
- [ ] documentation
- [x] bugfix
- [ ] new feature
- [ ] refactor
- [ ] security/CVE
- [ ] other

2024-11-08 13:16 UTC, nattilabalint approved these changes

2024-11-19 15:11 UTC, viktorsomogyi approved these changes
@mhratson would you please review this?

2024-11-21 09:15 UTC, viktorsomogyi commented
@CCisGG would you review this please if you have some time?

2025-01-04 15:56 UTC, imans777 commented
?

2025-01-07 10:42 UTC, k0b3rIT commented
> ?

Hi @imans777,
Do you have a concern regarding this change?

2025-01-07 17:27 UTC, CCisGG requested changes

2025-01-07 17:27 UTC, CCisGG commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
>                                                AnalyzerConfig.GOALS_CONFIG, interBrokerGoalNames));
Looks like you also need to update the exception logs to make it more clear.

2025-01-07 17:28 UTC, CCisGG commented
To me, allowing intra broker goals to be added into default goals is a valid intention. I'm just trying to make sure this won't break users who don't use intra broker goals. From the code change, looks like it won't.

2025-01-07 20:33 UTC, k0b3rIT commented
> To me, allowing intra broker goals to be added into default goals is a valid intention. I'm just trying to make sure this won't break users who don't use intra broker goals. From the code change, looks like it won't.

@CCisGG thanks for your feedback.
My understanding is that intra.broker.goals is just a list of supported intra goals, just like the goals is the list of supported inter goals.
There is no other way to enable the intra broker roles, other than adding it to the default goals.

But now it is not possible, just with the mentioned workaround.
So I dont think it will break anyone.

2025-01-08 10:02 UTC, k0b3rIT commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java
>                                                AnalyzerConfig.GOALS_CONFIG, interBrokerGoalNames));
You are right, I have fixed it!

2025-01-08 16:09 UTC, CCisGG approved these changes

2025-01-08 16:10 UTC, imans777 commented
> > ?
> 
> Hi @imans777, Do you have a concern regarding this change?

Hey there, I just wanted to pop up this change to be reviewed and merged sooner :)

2025-01-09 07:54 UTC, k0b3rIT commented
> > > ?
> > 
> > 
> > Hi @imans777, Do you have a concern regarding this change?
> 
> Hey there, I just wanted to pop up this change to be reviewed and merged sooner :)

Ahh, got it, THX!

2025-01-09 10:17 UTC, k0b3rIT commented
Thank you for the approval @CCisGG! Do you have write access to merge this PR?

2025-01-09 15:17 UTC, merged

2025-01-09 15:17 UTC, CCisGG commented
Merged. Thanks for the change!